"""remove is_anonymous from posts

Revision ID: 59fe3fbc8bc6
Revises: b30c96664230
Create Date: 2025-06-01 20:27:50.722739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fe3fbc8bc6'
down_revision: Union[str, None] = 'b30c96664230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_anonymous')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
