"""remove is_anonymous and likes from comments

Revision ID: 700a6b1725a9
Revises: cf441744f2da
Create Date: 2025-06-02 00:26:33.801230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700a6b1725a9'
down_revision: Union[str, None] = 'cf441744f2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_anonymous')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
