"""set section_id not null

Revision ID: 9aacf3db6945
Revises: 902332bc6639
Create Date: 2025-05-27 10:10:48.311197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aacf3db6945'
down_revision: Union[str, None] = '902332bc6639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
