"""add university_id to posts

Revision ID: bb2e7e994507
Revises: 27cfb74d9d79
Create Date: 2025-05-26 19:38:12.012807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2e7e994507'
down_revision: Union[str, None] = '27cfb74d9d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'university_id')
    # ### end Alembic commands ###
