"""set university_id not null

Revision ID: c82d08826668
Revises: bb2e7e994507
Create Date: 2025-05-26 19:45:35.783006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82d08826668'
down_revision: Union[str, None] = 'bb2e7e994507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'university_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'university_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
