"""remove comment_id from likes

Revision ID: cf441744f2da
Revises: 59fe3fbc8bc6
Create Date: 2025-06-01 20:41:15.683819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf441744f2da'
down_revision: Union[str, None] = '59fe3fbc8bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('unique_user_comment_like'), 'likes', type_='unique')
    op.drop_constraint(op.f('likes_comment_id_fkey'), 'likes', type_='foreignkey')
    op.drop_column('likes', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('likes_comment_id_fkey'), 'likes', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('unique_user_comment_like'), 'likes', ['user_id', 'comment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
