"""add university_id to users

Revision ID: d77a6b9330c0
Revises: 9aacf3db6945
Create Date: 2025-05-27 18:26:20.754924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77a6b9330c0'
down_revision: Union[str, None] = '9aacf3db6945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'university_id')
    # ### end Alembic commands ###
