"""add activation token fields to user

Revision ID: ed3c2f16a242
Revises: cbc4475001f
Create Date: 2025-07-08 19:02:22.520156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3c2f16a242'
down_revision: Union[str, None] = 'cbc4475001f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('activation_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activation_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_token_expiry')
    op.drop_column('users', 'activation_token')
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
